[[PRIMA]]
arch = "aarch64"
git-tree-sha1 = "ed5f9ebea32dce22f97bf9c91235848a9feebbcb"
libgfortran_version = "5.0.0"
os = "macos"

    [[PRIMA.download]]
    sha256 = "70045c27cebb4db61e945c903731198b6195cfab6632a792f35f1c57f33a73c1"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PRIMA]]
arch = "aarch64"
git-tree-sha1 = "54fa5b62d081648c05423b0b24ff90e8ba320091"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "ec44a106046bd79a2cb4cc5d28b8fffb324b4bed7a72bb424a53acc824954b1f"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PRIMA]]
arch = "aarch64"
git-tree-sha1 = "e36331244a549bdbe047285bd6333888eee0b7ae"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "fbbce9e75239bbe36901302fcca339e631a436f82df35dee47bd58786059a09e"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PRIMA]]
arch = "aarch64"
git-tree-sha1 = "9b1728180a26c890a98285be4cb58f5d4581f05c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "f7602674ab7eefbc5f27839542dc27eac0b2769c85adcd5b7e333111b483ea0c"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[PRIMA]]
arch = "aarch64"
git-tree-sha1 = "6c76b44f1d1337e15468b0dc5c185ca998271e35"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "874dfd199f9401d97158b92574d397c8c3ee77d542706ddc969a8309e91bc50e"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[PRIMA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8de1a0ba9af2ea8b71f5c8eac0232b908dbff626"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "d4adb7794664b20b4bd0e38133469316520af00dbac4509fb5dfabec036bf39e"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PRIMA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "faa55bdd2d1f52e76ee293ce2f77cc37572e3da7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "7c10da26f6ae10c3a042ac71f96f8398987e6218925b462a830782dc5e3b7ec7"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PRIMA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1424e173b01c827a665798b50da075fb6579f936"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "9517ce8ec2008f861532a6d0def11b44f2b113e326d2b2ead23b39a668cc87f2"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PRIMA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c9bbce72f3dfa55dfbcd78da475118026717e953"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "988ad03e4d8fb8f2b17951c259c78ff5a12b3fa3402c95538d0671312d6a4684"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PRIMA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "835f6e22c2e8852468dbbba41d8411a20f80c538"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "9c7291ad8e9e26be24aeef68218fd905e8aa056eab7b3d6aed6b07c9c618a953"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PRIMA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ebac5ec8d00379691e2e4e9cf92c6874234a351"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "caee91534423e709381607f47d9370f00051489554b35c01c0f457ef77cea9c8"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PRIMA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "03efdc71d0df9d4c04a3f5ab93b35d9a2dddc483"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "48e070d2b448660c91a4f1e0efaeab647d9a86746e3bb2934355abaa8c12cbc2"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PRIMA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8e635e944fb05d1889313d7685abe886c79fc7c6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "05d19c28e9de08b10ab93ee461956edd93543788ba37e35d13a9d8d0ff99e386"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PRIMA]]
arch = "i686"
git-tree-sha1 = "0ae5b87c5f3ad54337a3d2fa975dddde95067d61"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "bb2f60029a58a522708acc7d1d82f52af764cb453f98ddd951fb84b61d98b20d"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.i686-linux-gnu-libgfortran4.tar.gz"
[[PRIMA]]
arch = "i686"
git-tree-sha1 = "d622a8bd8ff775813c68ac0aaeb575e70d92640a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "f745bb6524c2ea0bf0adf6298480e7c335212bed6bde7a48ffb337cd341817b5"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.i686-linux-gnu-libgfortran5.tar.gz"
[[PRIMA]]
arch = "i686"
git-tree-sha1 = "d62cbd398507fe8ac4716da3f57385617dd4a75d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "2617d2b52aaf2e8318f8a03e6f44caa92ccc58614721a19cc0ced3b987d19b93"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.i686-linux-musl-libgfortran4.tar.gz"
[[PRIMA]]
arch = "i686"
git-tree-sha1 = "23e31da00d7139a665e88353cbb78b7e547fba42"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "3207d7d0dc9b6c31552be889e138fb9cd6b3138e5471c3fd3c8cdd58989c4734"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.i686-linux-musl-libgfortran5.tar.gz"
[[PRIMA]]
arch = "i686"
git-tree-sha1 = "c1d086319eb72fafe6cd9d1688816013fe33265a"
libgfortran_version = "4.0.0"
os = "windows"

    [[PRIMA.download]]
    sha256 = "821167061b49809fa39e4c8b5f2bb7ea2afd6d4a0149562a2b16d4a8da98079d"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[PRIMA]]
arch = "i686"
git-tree-sha1 = "bfcd67c7460fe89e31eeb497c9fc81185b141d80"
libgfortran_version = "5.0.0"
os = "windows"

    [[PRIMA.download]]
    sha256 = "652cc5e1d9b38721c9440e4b20152ac55e8f5a7c64a08576897bba2ab74f075d"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[PRIMA]]
arch = "powerpc64le"
git-tree-sha1 = "5fee1b572075de4d95493ec36cd1f891ba9a3048"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "f708b7eab8fa4e0e677b596a0f9500d98bd4dcb47722b368d72ed1c1afd61754"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PRIMA]]
arch = "powerpc64le"
git-tree-sha1 = "56c9795347147efc9ea904c3053465f4379f825a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "65e07c09493e2ae75ef6bb070a7c784dddf29b01e525974e3a98d9566d9d3989"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PRIMA]]
arch = "x86_64"
git-tree-sha1 = "2ee5eaeab88faa2f699cf6413a3f190299e16ebe"
libgfortran_version = "4.0.0"
os = "macos"

    [[PRIMA.download]]
    sha256 = "cb4a4603eaf100f9443731ba72e467a5ac1bb68e938d8138bf3925684de9b788"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PRIMA]]
arch = "x86_64"
git-tree-sha1 = "ef718065632e897d6ed256471d507bdf48b3580f"
libgfortran_version = "5.0.0"
os = "macos"

    [[PRIMA.download]]
    sha256 = "86f422554d2ad616eda343fae0e6970e296b9f57451245c350197d8cd82767f6"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PRIMA]]
arch = "x86_64"
git-tree-sha1 = "ae1f7c43e6cd375f1068776fc976f8f0680caaff"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "356a360558e94307409f3eee6e33d1efb4105df9b4a18e86487c4958a01e45ea"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PRIMA]]
arch = "x86_64"
git-tree-sha1 = "e9fe1c15f5b3873a7b260e9395ef9a49336bc333"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "d8398b8c0464f4e91bcfd92d40dfd126e7425cb101fe98c353477cdd0b328076"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PRIMA]]
arch = "x86_64"
git-tree-sha1 = "d85e58591f0215a55efe1c3a0aa09f9b13e49736"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "dacfc4bc5d82e3237ae8a5b03e24d80a2b2e417ce5413a61bb13da3c4e56a78c"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[PRIMA]]
arch = "x86_64"
git-tree-sha1 = "b8b4525833229f6c094d346bfe9ec403a33ce718"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PRIMA.download]]
    sha256 = "c9276857fa2c86796bc6fbf6df8f8a3331741de277b1b3a8d99ba434adcd3bbc"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[PRIMA]]
arch = "x86_64"
git-tree-sha1 = "05372183879cc30baa3e3f98c1466a8693899a19"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PRIMA.download]]
    sha256 = "cb5419fada39f2ff47b6b1c076430bfaa1680bb86c72f107f701c5d449463b04"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PRIMA]]
arch = "x86_64"
git-tree-sha1 = "acebc070b2b2476b8b396c23c2a38fe51f6806cd"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PRIMA.download]]
    sha256 = "15c9ba76e6a9d30e7d5f85b763a645f82145f52a5284a2aee7f872e538f89024"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PRIMA]]
arch = "x86_64"
git-tree-sha1 = "0e92dd5378884305358f44d085b60441935e86c7"
libgfortran_version = "4.0.0"
os = "windows"

    [[PRIMA.download]]
    sha256 = "e1169752982362b91f2ee9466d939784db7ef48962b70cd5f84bc9682143736d"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PRIMA]]
arch = "x86_64"
git-tree-sha1 = "5e14f8c2cddd7f9f70e662bdcf62183ad43f989d"
libgfortran_version = "5.0.0"
os = "windows"

    [[PRIMA.download]]
    sha256 = "a0260eb12a010f70c900ebe9520b64fdd7934595294c4c668ad8a0997ef88993"
    url = "https://github.com/JuliaBinaryWrappers/PRIMA_jll.jl/releases/download/PRIMA-v0.7.1+0/PRIMA.v0.7.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
